# merge 익히기

'풀이'만 수정하기

** 결과 셸은 실행하면 답이 사라져요!! **

In [1]:
# 데이터 불러오기
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/mergeTEst.csv',index_col= 0)
df.head()

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,55.08,53.107,51.267,49.560,47.983,46.453
Albania,11.803,10.807,9.943,9.267,8.79,8.493,8.363,8.363,8.453,8.597
Algeria,23.540,22.907,22.450,22.117,21.85,21.587,21.257,20.850,20.407,19.930
Andorra,4.240,4.033,3.843,3.667,3.49,3.330,3.187,3.060,2.933,2.827
Angola,75.713,71.280,67.233,63.570,60.43,57.757,55.510,53.460,51.757,50.093

## Q1.df1과 df2 데이터를 하나의 데이터 프레임으로 합쳐라

In [3]:
# data
df1 = df.iloc[:,:4]
df2 = df.iloc[:,4:]

display(df1)
display(df2)

                       2010    2011    2012    2013
Location
Afghanistan          64.023  61.640  59.367  57.170
Albania              11.803  10.807   9.943   9.267
Algeria              23.540  22.907  22.450  22.117
Andorra               4.240   4.033   3.843   3.667
Angola               75.713  71.280  67.233  63.570
Antigua and Barbuda   8.667   8.223   7.807   7.420
Argentina            12.887  12.380  11.840  11.283
Armenia              16.497  15.677  14.897  14.170
Australia             3.993   3.803   3.623   3.467
Austria               3.573   3.463   3.333   3.210

                       2014    2015    2016    2017    2018    2019
Location
Afghanistan          55.080  53.107  51.267  49.560  47.983  46.453
Albania               8.790   8.493   8.363   8.363   8.453   8.597
Algeria              21.850  21.587  21.257  20.850  20.407  19.930
Andorra               3.490   3.330   3.187   3.060   2.933   2.827
Angola               60.430  57.757  55.510  53.460  51.757  50.093
Antigua and Barbuda   7.070   6.757   6.483   6.230   6.000   5.783
Argentina            10.733  10.203   9.683   9.177   8.680   8.227
Armenia              13.477  12.817  12.183  11.583  11.007  10.497
Australia             3.343   3.253   3.183   3.137   3.090   3.047
Austria               3.113   3.043   2.987   2.943   2.897   2.843

In [7]:
# 풀이
res_df = pd.merge(df1, df2, on="Location")
res_df

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,55.080,53.107,51.267,49.560,47.983,46.453
Albania,11.803,10.807,9.943,9.267,8.790,8.493,8.363,8.363,8.453,8.597
Algeria,23.540,22.907,22.450,22.117,21.850,21.587,21.257,20.850,20.407,19.930
Andorra,4.240,4.033,3.843,3.667,3.490,3.330,3.187,3.060,2.933,2.827
Angola,75.713,71.280,67.233,63.570,60.430,57.757,55.510,53.460,51.757,50.093
Antigua and Barbuda,8.667,8.223,7.807,7.420,7.070,6.757,6.483,6.230,6.000,5.783
Argentina,12.887,12.380,11.840,11.283,10.733,10.203,9.683,9.177,8.680,8.227
Armenia,16.497,15.677,14.897,14.170,13.477,12.817,12.183,11.583,11.007,10.497
Australia,3.993,3.803,3.623,3.467,3.343,3.253,3.183,3.137,3.090,3.047
Austria,3.573,3.463,3.333,3.210,3.113,3.043,2.987,2.943,2.897,2.843

In [ ]:
#결과
res_df

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Location,,,,,,,,,,
Afghanistan,64.023,61.640,59.367,57.170,55.080,53.107,51.267,49.560,47.983,46.453
Albania,11.803,10.807,9.943,9.267,8.790,8.493,8.363,8.363,8.453,8.597
Algeria,23.540,22.907,22.450,22.117,21.850,21.587,21.257,20.850,20.407,19.930
Andorra,4.240,4.033,3.843,3.667,3.490,3.330,3.187,3.060,2.933,2.827
Angola,75.713,71.280,67.233,63.570,60.430,57.757,55.510,53.460,51.757,50.093
Antigua and Barbuda,8.667,8.223,7.807,7.420,7.070,6.757,6.483,6.230,6.000,5.783
Argentina,12.887,12.380,11.840,11.283,10.733,10.203,9.683,9.177,8.680,8.227
Armenia,16.497,15.677,14.897,14.170,13.477,12.817,12.183,11.583,11.007,10.497
Australia,3.993,3.803,3.623,3.467,3.343,3.253,3.183,3.137,3.090,3.047
Austria,3.573,3.463,3.333,3.210,3.113,3.043,2.987,2.943,2.897,2.843

## Q2.df3과 df4 데이터를 하나의 데이터 프레임으로 합쳐라(둘 다 포함하고 있는 년도에 대해서만)

In [5]:
# data
df3 = df.iloc[:2,:4].T
df3.index.names = ['year']

df4 = df.iloc[5:,3:].T
df4.index.names = ['year']

display(df3)
display(df4)

Location  Afghanistan  Albania
year
2010           64.023   11.803
2011           61.640   10.807
2012           59.367    9.943
2013           57.170    9.267

Location  Antigua and Barbuda  Argentina  Armenia  Australia  Austria
year
2013                    7.420     11.283   14.170      3.467    3.210
2014                    7.070     10.733   13.477      3.343    3.113
2015                    6.757     10.203   12.817      3.253    3.043
2016                    6.483      9.683   12.183      3.183    2.987
2017                    6.230      9.177   11.583      3.137    2.943
2018                    6.000      8.680   11.007      3.090    2.897
2019                    5.783      8.227   10.497      3.047    2.843

In [7]:
# 풀이

In [ ]:
#결과
res_df

Location,Afghanistan,Albania,Antigua and Barbuda,Argentina,Armenia,Australia,Austria
year,,,,,,,
2013,57.17,9.267,7.42,11.283,14.17,3.467,3.21

## Q3.df3과 df4 데이터를 하나의 데이터 프레임으로 합쳐라. 모든 컬럼을 포함하고, 결측치는 0으로 대체한다

In [ ]:
# data
df3 = df.iloc[:2,:4].T
df3.index.names = ['year']

df4 = df.iloc[5:,3:].T
df4.index.names = ['year']

display(df3)
display(df4)

Location  Afghanistan  Albania
year
2010           64.023   11.803
2011           61.640   10.807
2012           59.367    9.943
2013           57.170    9.267

Location  Antigua and Barbuda  Argentina  Armenia  Australia  Austria
year
2013                    7.420     11.283   14.170      3.467    3.210
2014                    7.070     10.733   13.477      3.343    3.113
2015                    6.757     10.203   12.817      3.253    3.043
2016                    6.483      9.683   12.183      3.183    2.987
2017                    6.230      9.177   11.583      3.137    2.943
2018                    6.000      8.680   11.007      3.090    2.897
2019                    5.783      8.227   10.497      3.047    2.843

In [10]:
# 풀이

In [ ]:
# 결과
res_df

Location,Afghanistan,Albania,Antigua and Barbuda,Argentina,Armenia,Australia,Austria
year,,,,,,,
2010,64.023,11.803,0.000,0.000,0.000,0.000,0.000
2011,61.640,10.807,0.000,0.000,0.000,0.000,0.000
2012,59.367,9.943,0.000,0.000,0.000,0.000,0.000
2013,57.170,9.267,7.420,11.283,14.170,3.467,3.210
2014,0.000,0.000,7.070,10.733,13.477,3.343,3.113
2015,0.000,0.000,6.757,10.203,12.817,3.253,3.043
2016,0.000,0.000,6.483,9.683,12.183,3.183,2.987
2017,0.000,0.000,6.230,9.177,11.583,3.137,2.943
2018,0.000,0.000,6.000,8.680,11.007,3.090,2.897
2019,0.000,0.000,5.783,8.227,10.497,3.047,2.843

## Q4.df5와 df6 데이터를 하나의 데이터 프레임으로 merge를 사용하여 합쳐라. Algeria 컬럼을 key로 하고 두 데이터를 모두 포함하는 데이터만 출력하라

In [11]:
# data
df5 = df.T.iloc[:7,:3]
df6 = df.T.iloc[6:,2:5]

display(df5)
display(df6)

Location  Afghanistan  Albania  Algeria
2010           64.023   11.803   23.540
2011           61.640   10.807   22.907
2012           59.367    9.943   22.450
2013           57.170    9.267   22.117
2014           55.080    8.790   21.850
2015           53.107    8.493   21.587
2016           51.267    8.363   21.257

Location  Algeria  Andorra  Angola
2016       21.257    3.187  55.510
2017       20.850    3.060  53.460
2018       20.407    2.933  51.757
2019       19.930    2.827  50.093

In [13]:
# 풀이

In [ ]:
#결과
res_df

Location  Afghanistan  Albania  Algeria  Andorra  Angola
0              51.267    8.363   21.257    3.187   55.51

## Q5.df5과 df6 데이터를 하나의 데이터 프레임으로 merge함수를 이용하여 합쳐라. Algeria컬럼을 key로 하고 합집합으로 합쳐라

In [ ]:
# data
df5 = df.T.iloc[:7,:3]
df6 = df.T.iloc[6:,2:5]

display(df5)
display(df6)

Location  Afghanistan  Albania  Algeria
2010           64.023   11.803   23.540
2011           61.640   10.807   22.907
2012           59.367    9.943   22.450
2013           57.170    9.267   22.117
2014           55.080    8.790   21.850
2015           53.107    8.493   21.587
2016           51.267    8.363   21.257

Location  Algeria  Andorra  Angola
2016       21.257    3.187  55.510
2017       20.850    3.060  53.460
2018       20.407    2.933  51.757
2019       19.930    2.827  50.093

In [ ]:
# 풀이

In [ ]:
#결과
res_df

Location  Afghanistan  Albania  Algeria  Andorra  Angola
0              64.023   11.803   23.540      NaN     NaN
1              61.640   10.807   22.907      NaN     NaN
2              59.367    9.943   22.450      NaN     NaN
3              57.170    9.267   22.117      NaN     NaN
4              55.080    8.790   21.850      NaN     NaN
5              53.107    8.493   21.587      NaN     NaN
6              51.267    8.363   21.257    3.187  55.510
7                 NaN      NaN   20.850    3.060  53.460
8                 NaN      NaN   20.407    2.933  51.757
9                 NaN      NaN   19.930    2.827  50.093

# 정답

In [ ]:
# Q1
res_df = pd.merge(df1, df2, on = 'Location')

# Q2
res_df = pd.merge(df3, df4, on = 'year', how = 'inner')

# Q3
res_df = pd.merge(df3, df4, on = 'year', how = 'outer').fillna(0)

# Q4
res_df = pd.merge(df5, df6, on = 'Algeria', how = 'inner')

# Q5
res_df = pd.merge(df5, df6, on='Algeria', how='outer')